// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGy8HGPNhO6pMbEOvn48DN-iBEUg-3zRE',
    appId: '1:410231412391:web:23266a2574592679442d82',
    messagingSenderId: '410231412391',
    projectId: 'my-finance-tracking-5db71',
    authDomain: 'my-finance-tracking-5db71.firebaseapp.com',
    storageBucket: 'my-finance-tracking-5db71.firebasestorage.app',
    measurementId: 'G-9D1BKRWDSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl1u4oznSWJprOerV00H2iQZx_1_pGs7U',
    appId: '1:410231412391:android:7e2bcf327a45e9bd442d82',
    messagingSenderId: '410231412391',
    projectId: 'my-finance-tracking-5db71',
    storageBucket: 'my-finance-tracking-5db71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi9qgM_2AIaEyxJ-xbxUIxu3C1GtErzRM',
    appId: '1:410231412391:ios:3049df5dc4ded3ab442d82',
    messagingSenderId: '410231412391',
    projectId: 'my-finance-tracking-5db71',
    storageBucket: 'my-finance-tracking-5db71.firebasestorage.app',
    iosBundleId: 'com.example.myFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi9qgM_2AIaEyxJ-xbxUIxu3C1GtErzRM',
    appId: '1:410231412391:ios:3049df5dc4ded3ab442d82',
    messagingSenderId: '410231412391',
    projectId: 'my-finance-tracking-5db71',
    storageBucket: 'my-finance-tracking-5db71.firebasestorage.app',
    iosBundleId: 'com.example.myFinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGy8HGPNhO6pMbEOvn48DN-iBEUg-3zRE',
    appId: '1:410231412391:web:e6a7685e8be6c99c442d82',
    messagingSenderId: '410231412391',
    projectId: 'my-finance-tracking-5db71',
    authDomain: 'my-finance-tracking-5db71.firebaseapp.com',
    storageBucket: 'my-finance-tracking-5db71.firebasestorage.app',
    measurementId: 'G-TBQP8S0FW1',
  );
}
